import * as React from "react";
import Script from "next/script";
import Head from "next/head";
import Header from "../components/Header";
import Products from "./products";
import HowOrder from "../components/HowOrder";
import Contacts from "../components/Contacts";
import Footer from "../components/Footer";
import Features from "../components/Features";
import Feedback from "../components/Feedback";
import dynamic from "next/dynamic";

const Hero = dynamic(() => import("../components/Hero"));

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>
          Ковдри, подушки купити з доставкою у Харкові, Україні. Домашній
          текстиль Zevs
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Features />
      <React.Suspense fallback={<div>Loading...</div>}>
        <Products products={products} />
      </React.Suspense>
      <Feedback />
      <HowOrder />
      <Contacts />
      <Footer />
      <Script
        src="https://www.google-analytics.com/analytics.js"
        strategy="lazyOnload"
      />
    </>
  );
}
export async function getServerSideProps() {
  const response = await fetch(
    "https://testback-production-353f.up.railway.app/api/products"
  );
  const products = await response.json();

  return {
    props: { products },
  };
}
