import Script from "next/script";
import Head from "next/head";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Products from "../components/Products";
import HowOrder from "../components/HowOrder";
import Contacts from "../components/Contacts";
import Footer from "../components/Footer";
import Features from "../components/Features";
import Feedback from "../components/Feedback";





export default function Home({ products }) {

  return (
    <>
      <Head>
        <title>
          Ковдри, подушки купити з доставкою у Харкові, Україні. Домашній
          текстиль Zevs
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Features />
      <Products products={products} />
      <Feedback />
      <HowOrder />
      <Contacts />
      <Footer />
      <Script
        src="https://www.google-analytics.com/analytics.js"
        strategy="lazyOnload"
      />
    </>
  );
}

export async function getServerSideProps() {
  try {
    const res = await fetch("https://testback-production-353f.up.railway.app/api/products");
    if (res.errors) {
      return { notFound: true };
    }
    const products = await res.json()

    return { props: { products } };
  } catch (e) {
    console.log(e)
    return { notFound: true };
  }

}
